Repository rakenduste-programmeerimine-2022/empathist, pull requests merged in 2022-11, with the labels that each got.

#49 user controller and routes added(closes #47 )
  server/models/user-model.js
Labels: BE

#58 user authentication FE (closes #15)
  client/src/components/global/Login.js
  client/src/components/global/Navbar.js
  client/src/components/global/Signup.js
Labels: FE

#80 74 add some eye pleasing features to the project
  client/src/App.css
  client/src/components/errors/Notification.jsx
  client/src/components/global/Navbar.js
  client/src/components/navbar/InteractiveLogo.jsx
  client/src/components/navbar/Logo.jsx
  client/src/css/navbar/logo.css
  client/src/img/head-logo.svg
  client/src/img/logo.svg
  client/src/pages/chat/Chat.js
  server/index.js
Labels: enhancement, FE
